### PR TITLE
Chrome Canary OSX and Xbox360 Controller Mappings

### PR DESCRIPTION
**Pull request by thejustinwalsh**
Not sure if chrome has changed their mappings from the initial version you built gamepad.js against, but when running on OS X against the latest canary build all of the xbox360 mappings are off.

I've merged the changes into my fork of gh-pages as well so you can test it out the latest code here...
http://thejustinwalsh.github.com/gamepad.js/example/

In addition to fixing the Xbox360 mappings, I also merged the Logitech controller into the proper source file.

Please let me know if these mappings are different for you in other versions of chrome, if they are we may need to take the browsers version number from the navigator.userAgent string into account to provide a better mapping experience.

### CODE REVIEW

**Comment by thejustinwalsh** [comment]
Just tested this code on Chrome 21 in the regular old release branch and the results are the same as canary.

**Comment by jensarps** [comment]
Can this be reviewed and merged? 21 now is the current version in the "regular" channel. Tested @thejustinwalsh's changes on Chrome 21 @ OSX Lion, and it works like a charm for me.

**Comment by thejustinwalsh** [comment]
👋

**Comment by jensarps** [comment]
Sweet memories 😃

**Comment by sgraham** [comment]
Sorry about that! I (obviously) didn't notice this at the time.

(FTR, I think the "standard mappings" built into browsers are supposed to handle the functionality of gamepad.js these days)

**Pull request closed without merging**
