### PR TITLE
Add support for Logitech F310 on OSX

### PR DESCRIPTION
**Pull request by tmpvar**
To test this, you'll need to turn the switch on the back to D instead of X before plugging it in.

### CODE REVIEW

**Comment by sgraham** [comment]
What driver did you install for this?

I'm hoping to fix this in-browser for Chromium, but I'll merge this for now. Thanks!

**Comment by tmpvar** [comment]
No driver, just flip the switch to D on the back of the controller before plugging it in :)

**Comment by sgraham** [comment]
Ah, Lion? Perhaps I need to get on that upgrade...

On Fri, Feb 10, 2012 at 5:29 PM, Elijah Insua <
reply@reply.github.com

**Comment by tmpvar** [comment]
oh, no.. 10.6

**Pull request merged**
